name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main
    workflow_dispatch:

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: jetli/wasm-pack-action@v0.4.0
              with:
                  # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
                  version: "latest"

            - name: Checkout
              uses: actions/checkout@v4

            - uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  rustflags: "-A warnings"

            - uses: actions/checkout@v4
              with:
                  repository: aspizu/goboscript
                  path: ./goboscript

            - run: |
                  cd goboscript
                  git checkout -b wasm
                  git pull origin main
                  wasm-pack build

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Install Dependencies
              run: bun install

            - name: Build
              run: bun run build

            - name: Upload Artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  name: github-pages
                  path: ./dist

    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: build
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deploy.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deploy
              uses: actions/deploy-pages@v4
